name: food_chef
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  rename: ^3.1.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^6.1.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.8
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_floating_bottom_bar: ^1.3.0
  flutter_local_notifications: ^20.1.0
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  get_it: ^9.2.0
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  skeletonizer: ^2.1.2
  vibration: ^3.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/
  fonts:
    - family: main
      fonts:
        - asset: fonts/Sen-Bold.ttf
        - asset: fonts/Sen-ExtraBold.ttf
        - asset: fonts/Sen-Medium.ttf
        - asset: fonts/Sen-Regular.ttf
        - asset: fonts/Sen-SemiBold.ttf
  uses-material-design: true
